on:
  push:
    branches:
      - deploy/review

jobs:
  job1:
    runs-on: ubuntu-latest
    name: job1 before deploy
    steps:
    - name: job1 step 1
      run: echo "job1 step 1"

  job2:
    runs-on: ubuntu-latest
    name: job2 before deploy
    needs: job1
    outputs:
      date: ${{ steps.getDate.outputs.date }}
    steps:
    - name: job2 step 1
      run: echo "job2 step 1"
    - name: create output data
      id: getDate
      run: echo "::set-output name=date::$(date +'%Y.%m.%d.%H.%M.%S')"

  deploy:
    runs-on: ubuntu-latest
    needs: job2
    environment:
      name: prod
    steps:
    - name: deploy step 1
      run: echo "env:prod@${{ needs.job2.outputs.date }}"

  deploy_test:
    runs-on: ubuntu-latest
    needs: job2
    environment:
      name: test
    steps:
    - name: deploy step 1
      run: echo "env:dev@${{ needs.job2.outputs.date }}"

  deploy_dev:
    runs-on: ubuntu-latest
    needs: job2
    environment:
      name: dev
    steps:
    - name: deploy step 1
      run: echo "env:dev@${{ needs.job2.outputs.date }}"


